In [5]:
import pandas as pd

s = pd.Series([10, 20, 30])
print(s)

0    10
1    20
2    30
dtype: int64

In [11]:
s = pd.Series([10, 20, 30],index=["a","b","c"])
print(s)
print(s["b"])

a    10
b    20
c    30
dtype: int64
20

In [13]:
import numpy as np
data = np.array([100, 200, 300])
s = pd.Series(data)
print(s.mean())
print(s.max())
print(s.value_counts())

200.0
300
100    1
200    1
300    1
dtype: int64

In [41]:
data = {
    "Name": ["A", "B", "C"],
    "Age": [23, 25, 21]
}

df = pd.DataFrame(data,columns=["id", "name"])
print(df)

Empty DataFrame
Columns: [id, name]
Index: []

In [39]:
data = [(1, "A"), (2, "B"), (3, "C")]

df = pd.DataFrame.from_records(data, columns=["id", "name"])
print(df)

   id name
0   1    A
1   2    B
2   3    C

In [45]:
data = [(1, "A"), (2, "B")]

df1 = pd.DataFrame(data, columns=["id", "name"])
df2 = pd.DataFrame.from_records(data, columns=["id", "name"])
df1

   id name
0   1    A
1   2    B

In [46]:
df2

   id name
0   1    A
1   2    B

In [ ]:
print(df.loc[0,"Name"])    # label-based loc[row,col] example loc[:row,:col] integers and strings
print(df.iloc[0])     # index-based iloc[row,col] example iloc[:row,:col] only integers

A
Name     A
Age     23
Name: 0, dtype: object

In [21]:
#Feature engineering example.
df["Age_plus_5"] = df["Age"] + 5
print(df)

  Name  Age  Age_plus_5
0    A   23          28
1    B   25          30
2    C   21          26

In [26]:
print("Shape",df.shape)
print("Column",df.columns)
print("Type",df.dtypes)

Shape (3, 3)
Column Index(['Name', 'Age', 'Age_plus_5'], dtype='object')
Type Name          object
Age            int64
Age_plus_5     int64
dtype: object

In [2]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset("titanic")
#print(df)
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [3]:
df.shape

(891, 15)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [5]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [6]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [7]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [8]:
age_series = df["age"]
type(age_series)

pandas.core.series.Series

In [10]:
age_series.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [11]:
age_series.mean()
age_series.max()
age_series.min()

0.42

In [12]:
age_series.isnull().sum()

177

In [13]:
target = df["survived"]
target.value_counts()

0    549
1    342
Name: survived, dtype: int64

In [14]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [16]:
df.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [20]:
df[["age", "fare"]].head()

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [21]:
df["family_size"] = df["sibsp"] + df["parch"] + 1
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,2
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1

In [24]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
family_size      0
dtype: int64

In [27]:
df["age"] > 60
df
#df[df["age"] > 60]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,2
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,1
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,1
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,4
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,1
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,1

In [ ]:
#df["age"] > 60

df[df["age"] > 60]
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,2
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,1
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,1
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,4
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,1
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,1

In [30]:
df.describe(include="all")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,891,891,891,203,889,891,891,891.000000
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2,NaN
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True,NaN
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537,NaN
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.904602
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.613459
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000
max,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.000000

In [36]:
#Always separate target early
X = df.drop("survived", axis=1)
y = df["survived"]
X

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size
0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2
1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2
2,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1
3,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,2
4,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,1
887,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,1
888,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,4
889,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,1
890,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,1

In [38]:
df_copy = df.copy()
df_copy

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,2
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,1
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,1
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,4
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,1
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,1

In [48]:
df_copy["age"] > 60

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: age, Length: 891, dtype: bool

In [50]:
type(df_copy["age"] > 60)

pandas.core.series.Series

In [52]:
df_copy[df_copy["age"] > 60]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size
33,0,2,male,66.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True,1
54,0,1,male,65.0,0,1,61.9792,C,First,man,True,B,Cherbourg,no,False,2
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True,1
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,1
170,0,1,male,61.0,0,0,33.5000,S,First,man,True,B,Southampton,no,True,1
252,0,1,male,62.0,0,0,26.5500,S,First,man,True,C,Southampton,no,True,1
275,1,1,female,63.0,1,0,77.9583,S,First,woman,False,D,Southampton,yes,False,2
280,0,3,male,65.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,1
326,0,3,male,61.0,0,0,6.2375,S,Third,man,True,NaN,Southampton,no,True,1
438,0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False,6
456,0,1,male,65.0,0,0,26.5500,S,First,man,True,E,Southampton,no,True,1
483,1,3,female,63.0,0,0,9.5875,S,Third,woman,False,NaN,Southampton,yes,True,1
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True,1
545,0,1,male,64.0,0,0,26.0000,S,First,man,True,NaN,Southampton,no,True,1
555,0,1,male,62.0,0,0,26.5500,S,First,man,True,NaN,Southampton,no,True,1
570,1,2,male,62.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,yes,True,1
625,0,1,male,61.0,0,0,32.3208,S,First,man,True,D,Southampton,no,True,1
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True,1
672,0,2,male,70.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True,1
745,0,1,male,70.0,1,1,71.0000,S,First,man,True,B,Southampton,no,False,3
829,1,1,female,62.0,0,0,80.0000,NaN,First,woman,False,B,NaN,yes,True,1
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True,1

In [63]:
older_passengers=df_copy[df_copy["age"] >50]
older_passengers[["age","fare","survived"]]

      age     fare  survived
6    54.0  51.8625         0
11   58.0  26.5500         1
15   55.0  16.0000         1
33   66.0  10.5000         0
54   65.0  61.9792         0
..    ...      ...       ...
820  52.0  93.5000         1
829  62.0  80.0000         1
851  74.0   7.7750         0
857  51.0  26.5500         1
879  56.0  83.1583         1

[64 rows x 3 columns]

In [71]:
df_copy["high_fare"]=(df_copy["fare"]>100).astype(int)
df_copy
df_copy["high_fare"].sum()

53

In [72]:
df_copy.isnull().sum().sort_values(ascending=False)

deck           688
age            177
embark_town      2
embarked         2
survived         0
adult_male       0
family_size      0
alone            0
alive            0
class            0
who              0
pclass           0
fare             0
parch            0
sibsp            0
sex              0
high_fare        0
dtype: int64

In [74]:
df_copy["survived"].value_counts()

0    549
1    342
Name: survived, dtype: int64

In [ ]:
df_copy.describe().loc["std"].sort_values(ascending=False)

fare           49.693429
age            14.526497
family_size     1.613459
sibsp           1.102743
pclass          0.836071
parch           0.806057
survived        0.486592
high_fare       0.236661
Name: std, dtype: float64