In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Step 1: Data Loading and Initial Exploration

In [12]:
customers=pd.read_csv("customers.csv")
print(customers.head())
print(customers.shape)
print(customers.info())
#print("Duplicates",customers.duplicated().sum)
print(customers["customer_id"].nunique()) #primary key
print(customers.shape[0])
print(customers["customer_unique_id"].nunique())
print(customers.shape[0])

                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
2                      1151              sao paulo             SP
3                      8775        mogi das cruzes             SP
4                     13056               campinas             SP
(99441, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB
None
99441
99441
96096
99441

In [13]:
orders=pd.read_csv("orders.csv")
print(orders.head())
print(orders.shape)
print(orders.info())
print(orders.isnull().sum())
#print("Duplicates",orders.duplicated().sum) 
print(orders["customer_id"].nunique())#foreign key
print(orders.shape[0])
print(orders["order_id"].nunique()) #primary key
print(orders["customer_id"].isin(customers["customer_id"]).all())

                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date
0           2017-10-18 00:00:00
1           2018-08-13 00:00:00
2           2018-09-04 00:00:00
3           2017-12-15 00:00:00
4           2018-02-26 00:00:00
(99441, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB
None
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
99441
99441
99441
True

In [5]:
order_items = pd.read_csv("order_item.csv")
print(order_items.head())
print(order_items.shape)
print(order_items.isnull().sum())
print(order_items["order_id"].nunique()) #foreign key
print(order_items["order_item_id"].nunique()) #primary key
print(order_items["product_id"].nunique()) #foreign key
print(order_items["seller_id"].nunique()) #foreign key
print(order_items[["order_id", "order_item_id"]].drop_duplicates().shape[0]) #composite primary key
print(order_items.shape[0])

                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1
2  000229ec398224ef6ca0657da4fc703e              1
3  00024acbcdf0a6daa1e931b038114c75              1
4  00042b26cf59d7ce69dfabb4e55b4fd9              1

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87

   shipping_limit_date   price  freight_value
0  2017-09-19 09:45:35   58.90          13.29
1  2017-05-03 11:05:13  239.90          19.93
2  2018-01-18 14:48:30  199.00          17.87
3  2018-08-15 10:10:18   12.99          12.79
4  2017-02-13 13:57:51  199.90          18.14
(112650, 7)
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64
98666
21
32951
3095
112650
112650

In [6]:
payments = pd.read_csv("payments.csv")
print(payments.head())
print(payments.shape)
print(payments.isnull().sum())
print(payments["order_id"].nunique()) #foreign key
print(payments["payment_type"].nunique())
print(payments["payment_type"].value_counts())
print(payments['payment_sequential'].nunique()) #primary key
print(payments[["order_id", "payment_sequential"]].drop_duplicates().shape[0]) #composite primary key
print(payments.shape[0])

                           order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card

   payment_installments  payment_value
0                     8          99.33
1                     1          24.39
2                     1          65.71
3                     8         107.78
4                     2         128.45
(103886, 5)
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64
99440
5
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: payment_type, dtype: int64
29
103886
103886

In [7]:
reviews = pd.read_csv("reviews.csv")
print(reviews.head())
print(reviews.shape)
print(reviews.isnull().sum())
print(reviews["review_id"].nunique()) #primary key
print(reviews["order_id"].nunique()) #foreign key
print(reviews["review_score"].nunique())
print(reviews["review_score"].value_counts())

                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1

   review_score review_comment_title  \
0             4                  NaN
1             5                  NaN
2             5                  NaN
3             5                  NaN
4             5                  NaN

                              review_comment_message review_creation_date  \
0                                                NaN  2018-01-18 00:00:00
1                                                NaN  2018-03-10 00:00:00
2                                                NaN  2018-02-17 00:00:00
3              Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00
4  Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00

  review_answer_timestamp
0     2018-01-18 21:46:59
1     2018-03-11 03:05:13
2     2018-02-18 14:36:24
3     2017-04-21 22:02:06
4     2018-03-02 10:26:53
(99224, 7)
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64
98410
98673
5
5    57328
4    19142
1    11424
3     8179
2     3151
Name: review_score, dtype: int64

In [20]:
products = pd.read_csv("products.csv")
print(products.head())
print(products.shape)
print(products.isnull().sum())
print(products["product_id"].nunique()) #primary key
print(products["product_category_name"].nunique()) #foreign key to categpory_name_translation table
#print(products["product_category_name"].value_counts())

                         product_id  product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer
3  cef67bcfe19066a932b7673e239eb23d                  bebes
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0
1                 44.0                       276.0                 1.0
2                 46.0                       250.0                 1.0
3                 27.0                       261.0                 1.0
4                 37.0                       402.0                 4.0

   product_weight_g  product_length_cm  product_height_cm  product_width_cm
0             225.0               16.0               10.0              14.0
1            1000.0               30.0               18.0              20.0
2             154.0               18.0                9.0              15.0
3             371.0               26.0                4.0              26.0
4             625.0               20.0               17.0              13.0
(32951, 9)
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64
32951
73

In [9]:
sellers = pd.read_csv("sellers.csv")
print(sellers.head())
print(sellers.shape)
print(sellers.isnull().sum())
print(sellers["seller_id"].nunique()) #primary key
print(sellers["seller_zip_code_prefix"].nunique())
print(sellers["seller_city"].nunique())
print(sellers["seller_state"].nunique())

                          seller_id  seller_zip_code_prefix  \
0  3442f8959a84dea7ee197c632cb2df15                   13023
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914

         seller_city seller_state
0           campinas           SP
1         mogi guacu           SP
2     rio de janeiro           RJ
3          sao paulo           SP
4  braganca paulista           SP
(3095, 4)
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64
3095
2246
611
23

In [10]:
category_name_translation = pd.read_csv("category_translation.csv")
print(category_name_translation.head())
print(category_name_translation.shape)
print(category_name_translation.isnull().sum())
print(category_name_translation["product_category_name"].nunique()) #primary key
print(category_name_translation["product_category_name_english"].nunique()) #foreign key to products table

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor
(71, 2)
product_category_name            0
product_category_name_english    0
dtype: int64
71
71

Step 2: Data Cleaning and Preprocessing

•	Handle missing values appropriately

In [ ]:
#Check for missing values in each dataset
# print("Customers:\n",customers.isnull().sum())
# print("Orders:\n",orders.isnull().sum())
# print("Order Items:\n",order_items.isnull().sum())
# print("Payments:\n",payments.isnull().sum())
# print("Reviews:\n",reviews.isnull().sum())
# print("Products:\n",products.isnull().sum())
# print("Sellers:\n",sellers.isnull().sum())
# print("Category Name Translation:\n",category_name_translation.isnull().sum())
tables = {
    "orders": orders,
    "customers": customers,
    "order_items": order_items,
    "payments": payments,
    "reviews": reviews,
    "products": products,
    "sellers": sellers,
    "category_name_translation": category_name_translation
}
for name, df in tables.items():
    null_count = df.isnull().sum()
    null_count = null_count[null_count > 0]
    print(f"\n {name}:")
    if null_count.empty:
        print("  No missing values")
    else:
        print(null_count)

 orders:
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
dtype: int64

 customers:
  No missing values

 order_items:
  No missing values

 payments:
  No missing values

 reviews:
review_comment_title      87656
review_comment_message    58247
dtype: int64

 products:
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

 sellers:
  No missing values

 category_name_translation:
  No missing values

In [ ]:
# Check order_status distribution first
print(orders["order_status"].value_counts())
orders = orders[orders["order_status"] == "delivered"]
print(orders.shape)
print(orders.isnull().sum())

delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: order_status, dtype: int64
(96478, 8)
order_id                          0
customer_id                       0
order_status                      0
order_purchase_timestamp          0
order_approved_at                14
order_delivered_carrier_date      2
order_delivered_customer_date     8
order_estimated_delivery_date     0
dtype: int64

In [17]:
# Drop remaining null rows in orders
orders = orders.dropna(subset=["order_approved_at","order_delivered_carrier_date", "order_delivered_customer_date"])
# Verify
print(orders.shape)
print(orders.isnull().sum())

(96455, 8)
order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
dtype: int64

In [18]:
# First check review_score nulls
print(reviews.isnull().sum())
print(reviews.shape)
# Also check
print(reviews["review_score"].value_counts())

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64
(99224, 7)
5    57328
4    19142
1    11424
3     8179
2     3151
Name: review_score, dtype: int64

In [19]:
reviews["review_comment_title"].fillna("No Title", inplace=True)
reviews["review_comment_message"].fillna("No Comment", inplace=True)
print(reviews.isnull().sum())
print(reviews.shape)

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64
(99224, 7)

In [22]:
print(products.shape)
# Checking if same 610 rows are null across all columns
null_mask = products["product_category_name"].isnull()
print(products[null_mask].tail())

(32951, 9)
                             product_id product_category_name  \
32515  b0a0c5dd78e644373b199380612c350a                   NaN
32589  10dbe0fbaa2c505123c17fdc34a63c56                   NaN
32616  bd2ada37b58ae94cc838b9c0569fecd8                   NaN
32772  fa51e914046aab32764c41356b9d4ea4                   NaN
32852  c4ceee876c82b8328e9c293fa0e1989b                   NaN

       product_name_lenght  product_description_lenght  product_photos_qty  \
32515                  NaN                         NaN                 NaN
32589                  NaN                         NaN                 NaN
32616                  NaN                         NaN                 NaN
32772                  NaN                         NaN                 NaN
32852                  NaN                         NaN                 NaN

       product_weight_g  product_length_cm  product_height_cm  \
32515            1800.0               30.0               20.0
32589             800.0               30.0               10.0
32616             200.0               21.0                8.0
32772            1300.0               45.0               16.0
32852             700.0               28.0                3.0

       product_width_cm
32515              70.0
32589              23.0
32616              16.0
32772              45.0
32852              43.0

In [23]:
# Fill category name with Unknown
products["product_category_name"].fillna("Unknown", inplace=True)
# Fill numeric columns with median
numeric_cols = ["product_name_lenght", 
                "product_description_lenght",
                "product_photos_qty",
                "product_weight_g",
                "product_length_cm", 
                "product_height_cm", 
                "product_width_cm"]

for col in numeric_cols:
    products[col].fillna(products[col].median(), inplace=True)
print(products.isnull().sum())
print(products.shape)

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64
(32951, 9)

•	Remove duplicate records

In [24]:
tables = {
    "orders": orders,
    "customers": customers,
    "order_items": order_items,
    "payments": payments,
    "reviews": reviews,
    "products": products,
    "sellers": sellers,
    "category_name_translation": category_name_translation
}
for name, df in tables.items():
    print(f"{name} duplicates: {df.duplicated().sum()}")

orders duplicates: 0
customers duplicates: 0
order_items duplicates: 0
payments duplicates: 0
reviews duplicates: 0
products duplicates: 0
sellers duplicates: 0
category_name_translation duplicates: 0

•	Convert date columns to datetime format

In [25]:
# Convert date columns to datetime for orders
date_cols_orders = ["order_purchase_timestamp",
                    "order_approved_at",
                    "order_delivered_carrier_date",
                    "order_delivered_customer_date",
                    "order_estimated_delivery_date"]

for col in date_cols_orders:
    orders[col] = pd.to_datetime(orders[col])
# for order_items
order_items["shipping_limit_date"] = pd.to_datetime(order_items["shipping_limit_date"])
# reviews
date_cols_reviews = ["review_creation_date", 
                     "review_answer_timestamp"]

for col in date_cols_reviews:
    reviews[col] = pd.to_datetime(reviews[col])
# Check dtypes
print("orders dtypes:\n", orders.dtypes)
print("\norder_items dtypes:\n", order_items.dtypes)
print("\nreviews dtypes:\n", reviews.dtypes)

orders dtypes:
 order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

order_items dtypes:
 order_id                       object
order_item_id                   int64
product_id                     object
seller_id                      object
shipping_limit_date    datetime64[ns]
price                         float64
freight_value                 float64
dtype: object

reviews dtypes:
 review_id                          object
order_id                           object
review_score                        int64
review_comment_title               object
review_comment_message             object
review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object

•	Validate data types and ranges

In [ ]:
# 1. price and freight should be positive
print("Negative prices:", (order_items["price"] <= 0).sum())
print("Negative freight:", (order_items["freight_value"] <= 0).sum())
# 2. review_score should be between 1-5
print("Invalid review scores:", reviews[~reviews["review_score"].between(1, 5)].shape[0])
# 3. payment_value should be positive
print("Negative payments:", (payments["payment_value"] <= 0).sum())
# 4. products numeric ranges
print("Negative weight:", (products["product_weight_g"] <= 0).sum())
print("Negative dimensions:", ((products["product_length_cm"] <= 0) |(products["product_height_cm"] <= 0) |(products["product_width_cm"] <= 0)).sum())

Negative prices: 0
Negative freight: 383
Invalid review scores: 0
Negative payments: 9
Negative weight: 4
Negative dimensions: 0

In [ ]:
# Check what these negative freight rows look like
print(order_items[order_items["freight_value"] <= 0][["order_id", "price", "freight_value"]])

Empty DataFrame
Columns: [order_id, price, freight_value]
Index: []

In [29]:
print("Negative payments:", (payments[payments["payment_value"] <= 0][["order_id", "payment_value"]]))

Negative payments:                                 order_id  payment_value
19922   8bcbe01d44d147f901cd3192671144db            0.0
36822   fa65dad1b0e818e3ccc5cb0e39231352            0.0
43744   6ccb433e00daae1283ccc956189c82ae            0.0
51280   4637ca194b6387e2d538dc89b124b0ee            0.0
57411   00b1cb0320190ca0daa2c88b35206009            0.0
62674   45ed6e85398a87c253db47c2d9f48216            0.0
77885   fa65dad1b0e818e3ccc5cb0e39231352            0.0
94427   c8c528189310eaa44a745b8d9d26908b            0.0
100766  b23878b3e8eb4d25a158f57d96331b18            0.0

In [31]:
# Check payment_type for these 0 value rows
print(payments[payments["payment_value"] <= 0][["order_id", "payment_type", "payment_value"]])

                                order_id payment_type  payment_value
19922   8bcbe01d44d147f901cd3192671144db      voucher            0.0
36822   fa65dad1b0e818e3ccc5cb0e39231352      voucher            0.0
43744   6ccb433e00daae1283ccc956189c82ae      voucher            0.0
51280   4637ca194b6387e2d538dc89b124b0ee  not_defined            0.0
57411   00b1cb0320190ca0daa2c88b35206009  not_defined            0.0
62674   45ed6e85398a87c253db47c2d9f48216      voucher            0.0
77885   fa65dad1b0e818e3ccc5cb0e39231352      voucher            0.0
94427   c8c528189310eaa44a745b8d9d26908b  not_defined            0.0
100766  b23878b3e8eb4d25a158f57d96331b18      voucher            0.0

In [32]:
# Drop only not_defined with 0 payment value
payments = payments[~((payments["payment_type"] == "not_defined") &  (payments["payment_value"] == 0.0))]
print(payments.shape)
print(payments["payment_type"].value_counts())

(103883, 5)
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
Name: payment_type, dtype: int64

In [36]:
print("Negative weight:", (products[products["product_weight_g"] <= 0][["product_id", "product_weight_g"]]))

Negative weight:                              product_id  product_weight_g
9769   81781c0fed9fe1ad6e8c81fca1e1cb08               0.0
13683  8038040ee2a71048d4bdbbdc985b69ab               0.0
14997  36ba42dd187055e1fbe943b2d11430ca               0.0
32079  e673e90efa65a5409ff4196c038bb5af               0.0

In [37]:
# Replace 0 weight with median
median_weight = products[products["product_weight_g"] > 0]["product_weight_g"].median()
products.loc[products["product_weight_g"] == 0, "product_weight_g"] = median_weight
print("Zero weights remaining:", (products["product_weight_g"] == 0).sum())
print("Median weight used:", median_weight)

Zero weights remaining: 0
Median weight used: 700.0

•	Standardize column names if required

In [ ]:
# All column check
for name, df in tables.items():
    print(f"\n{name}: {list(df.columns)}")

orders: ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

customers: ['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

order_items: ['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

payments: ['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

reviews: ['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

products: ['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

sellers: ['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

category_name_translation: ['product_category_name', 'product_category_name_english']

In [40]:
products.rename(columns={
    "product_name_lenght": "product_name_length",
    "product_description_lenght": "product_description_length"
}, inplace=True)
print(products.columns.tolist())

['product_id', 'product_category_name', 'product_name_length', 'product_description_length', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

Step 3: Data Integration (Critical Component)

In [51]:
# Step 1 — orders + customers
master = orders.merge(customers, on="customer_id", how="left")
master.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP

In [49]:
print(orders.shape)
print(customers.shape)
print(master.shape)

(96455, 8)
(99441, 5)
(96455, 12)

In [52]:
# Step 2 — master + order_items
master = master.merge(order_items, on="order_id", how="left")
master.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72

In [53]:
print(order_items.shape)
print(master.shape)

(112650, 7)
(110173, 18)

In [54]:
# Step 3 — master + products
master = master.merge(products, on="product_id", how="left")
master.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,price,freight_value,product_category_name,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,118.70,22.76,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,159.90,19.22,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,...,45.00,27.20,pet_shop,59.0,468.0,3.0,450.0,30.0,10.0,20.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,19.90,8.72,papelaria,38.0,316.0,4.0,250.0,51.0,15.0,15.0

In [55]:
print(products.shape)
print(master.shape)

(32951, 9)
(110173, 26)

In [56]:
# Step 4 — master + category_name_translation
master = master.merge(category_name_translation, on="product_category_name", how="left")
master.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,freight_value,product_category_name,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,housewares
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,22.76,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0,perfumery
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,19.22,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0,auto
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,...,27.20,pet_shop,59.0,468.0,3.0,450.0,30.0,10.0,20.0,pet_shop
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,8.72,papelaria,38.0,316.0,4.0,250.0,51.0,15.0,15.0,stationery

In [57]:
print(category_name_translation.shape)
print(master.shape)

(71, 2)
(110173, 27)

In [59]:
# Step 5 — master + payments
master = master.merge(payments, on="order_id", how="left")
master.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,payment_sequential,payment_type,payment_installments,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,4.0,500.0,19.0,8.0,13.0,housewares,1.0,credit_card,1.0,18.12
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,4.0,500.0,19.0,8.0,13.0,housewares,3.0,voucher,1.0,2.00
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,4.0,500.0,19.0,8.0,13.0,housewares,2.0,voucher,1.0,18.59
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,1.0,400.0,19.0,13.0,19.0,perfumery,1.0,boleto,1.0,141.46
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,1.0,420.0,24.0,19.0,21.0,auto,1.0,credit_card,3.0,179.12

In [60]:
print(payments.shape)
print(master.shape)

(103883, 5)
(115014, 31)

In [61]:
# Step 6 — master + reviews
master = master.merge(reviews, on="order_id", how="left")
master.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,1.0,credit_card,1.0,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,3.0,voucher,1.0,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,2.0,voucher,1.0,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,1.0,boleto,1.0,141.46,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08,2018-08-08 18:37:50
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,1.0,credit_card,3.0,179.12,e73b67b67587f7644d5bd1a52deb1b01,5.0,No Title,No Comment,2018-08-18,2018-08-22 19:07:58

In [62]:
print(reviews.shape)
print(master.shape)

(99224, 7)
(115699, 37)

In [63]:
master=master.merge(sellers, on="seller_id", how="left")
master.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,seller_zip_code_prefix,seller_city,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48,9350,maua,SP
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48,9350,maua,SP
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48,9350,maua,SP
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,141.46,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08,2018-08-08 18:37:50,31570,belo horizonte,SP
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,179.12,e73b67b67587f7644d5bd1a52deb1b01,5.0,No Title,No Comment,2018-08-18,2018-08-22 19:07:58,14840,guariba,SP

In [65]:
print(sellers.shape)
print(master.shape)
print(master.columns.tolist())

(3095, 4)
(115699, 40)
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value', 'product_category_name', 'product_name_length', 'product_description_length', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm', 'product_category_name_english', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value', 'review_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

In [74]:
master.head(3)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,seller_zip_code_prefix,seller_city,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48,9350,maua,SP
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48,9350,maua,SP
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,No Title,"Não testei o produto ainda, mas ele veio corre...",2017-10-11,2017-10-12 03:43:48,9350,maua,SP

In [75]:
print("Shape:\n",master.shape)
print("Null Values:\n", master.isnull().sum()[master.isnull().sum() > 0])
print("Data Types:\n", master.dtypes)

Shape:
 (115699, 40)
Null Values:
 product_category_name_english    1660
payment_sequential                  3
payment_type                        3
payment_installments                3
payment_value                       3
review_id                         861
review_score                      861
review_comment_title              861
review_comment_message            861
review_creation_date              861
review_answer_timestamp           861
dtype: int64
Data Types:
 order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
customer_unique_id                       object
customer_zip_code_prefix                  int64
customer_city                            object
customer_state                           object
order_item_id                             int64
product_id                               object
seller_id                                object
shipping_limit_date              datetime64[ns]
price                                   float64
freight_value                           float64
product_category_name                    object
product_name_length                     float64
product_description_length              float64
product_photos_qty                      float64
product_weight_g                        float64
product_length_cm                       float64
product_height_cm                       float64
product_width_cm                        float64
product_category_name_english            object
payment_sequential                      float64
payment_type                             object
payment_installments                    float64
payment_value                           float64
review_id                                object
review_score                            float64
review_comment_title                     object
review_comment_message                   object
review_creation_date             datetime64[ns]
review_answer_timestamp          datetime64[ns]
seller_zip_code_prefix                    int64
seller_city                              object
seller_state                             object
dtype: object

In [84]:
master[master["product_category_name_english"].isnull()][["product_category_name_english", "product_category_name"]]
#print("Null Values:\n", master.isnull())

       product_category_name_english product_category_name
126                              NaN               Unknown
215                              NaN               Unknown
268                              NaN               Unknown
309                              NaN               Unknown
381                              NaN               Unknown
...                              ...                   ...
115265                           NaN               Unknown
115437                           NaN               Unknown
115444                           NaN               Unknown
115450                           NaN               Unknown
115469                           NaN               Unknown

[1660 rows x 2 columns]

In [ ]:
# See what Portuguese categories have no English translation
print(master[master["product_category_name_english"].isnull()]["product_category_name"].value_counts())

Unknown                                          1637
portateis_cozinha_e_preparadores_de_alimentos      14
pc_gamer                                            9
Name: product_category_name, dtype: int64

In [86]:
# Compare both columns side by side
print(category_name_translation.head(10)[["product_category_name", "product_category_name_english"]])

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor
5           esporte_lazer                sports_leisure
6              perfumaria                     perfumery
7   utilidades_domesticas                    housewares
8               telefonia                     telephony
9      relogios_presentes                 watches_gifts

In [87]:
# Manual mapping for known Portuguese categories
master["product_category_name_english"] = master["product_category_name_english"].fillna(
    master["product_category_name"].map({
        "portateis_cozinha_e_preparadores_de_alimentos": "portable_kitchen_food_preparers",
        "pc_gamer": "pc_gamer",
        "Unknown": "Unknown"
    })
)
print(master["product_category_name_english"].isnull().sum())
print(master["product_category_name_english"].value_counts().tail(5))

0
portable_kitchen_food_preparers    14
cds_dvds_musicals                  14
pc_gamer                            9
fashion_childrens_clothes           7
security_and_services               2
Name: product_category_name_english, dtype: int64

In [90]:
# 1. payment nulls — only 3 rows, safe to drop
master = master.dropna(subset=["payment_value"])
# Check those 3 rows
print(master[master["payment_sequential"].isnull()][["order_id", "payment_value",  "payment_type", "payment_sequential"]])

Empty DataFrame
Columns: [order_id, payment_value, payment_type, payment_sequential]
Index: []

In [92]:
print("Null Values:\n", master.isnull().sum()[master.isnull().sum() > 0])

Null Values:
 review_id                  861
review_score               861
review_comment_title       861
review_comment_message     861
review_creation_date       861
review_answer_timestamp    861
dtype: int64

In [93]:
# review nulls — fill with neutral values
master["review_score"].fillna(0, inplace=True)
master["review_id"].fillna("No Review", inplace=True)
master["review_comment_title"].fillna("No Title", inplace=True)
master["review_comment_message"].fillna("No Comment", inplace=True)
master["review_creation_date"].fillna(pd.NaT, inplace=True)
master["review_answer_timestamp"].fillna(pd.NaT, inplace=True)

In [96]:
print("Shape:", master.shape)
print("Remaining nulls:\n", master.isnull().sum()[master.isnull().sum() > 0])

Shape: (115696, 40)
Remaining nulls:
 review_creation_date       861
review_answer_timestamp    861
dtype: int64

________________________________________
Step 4: Feature Engineering
________________________________________